### ISSUE TITLE
www/chromium does not start

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DPorts#108]
I installed chromium-35.0.1916.153_1. When I start <tt>chrome</tt> I get the following error messages:

    > chrome 
    sysctl: unknown oid 'kern.ipc.shm_allow_removed'
    [: =: unexpected operator
    [3998:102826176:0827/125807:ERROR:resource_bundle.cc(627)] Failed to load /usr/local/bin/chrome_100_percent.pak
    Some features may not be available.

And a dialog box opens with <tt>"Unable to find locale data files. Please reinstall."</tt>. Then, I am back at the command line.

**Comment by jrmarino** [comment]
Chromium was fixed a couple of weeks ago -- it starts now, at least on release 4.0 and the dev branch.
