### ISSUE TITLE
[: =: unexpected operator

### ISSUE THREAD

**Issue by bluesun08** [DragonFlyBSD/DPorts#124]
On DF 4.0.1 i executed:
pkg ins mysql55-server
rcenable mysql

Then i get:
[: =: unexpected operator
added/modified: mysql_enable=YES
Running /usr/local/etc/rc.d/mysql-server start
Starting mysql.

What is the reason for this error message "[: =: unexpected operator" and how can i solve this problem?

**Comment by jrmarino** [comment]
stalled.  Reopen if there's new information available.
