### ISSUE TITLE
x11-toolkits/gtk20 still depends on libpng15.so

### ISSUE THREAD

**Issue by davshao** [DragonFlyBSD/DPorts#128]
Makefile.DragonFly for x11-toolkits/gtk20 still has

LIB_DEPENDS+= libpng15.so:${PORTSDIR}/graphics/png

A quick grep shows that this issue may also affect 
x11-toolkits/gtk30's Makefile.DragonFly and
x11/bbdock's Makefile.

**Comment by jrmarino** [comment]
bbdock just hadn't been synced yet due to a missing header, but has now.
It seems that Makefile.DragonFly is no longer required for either gtk20 or gtk30, so its just been removed entirely.  Thanks!
