### ISSUE TITLE
 bash-completion: words: bad array subscript 

### ISSUE THREAD

**Issue by sigttou** [DragonFlyBSD/DPorts#131]
As in ubuntu bug report, TAB on empty line produces an unneded error message:
https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1289597

patch can be found in bug report. (https://code.launchpad.net/~j/bash-completion/bug1289597/+merge/210089)

**Comment by jrmarino** [comment]
FYI, freebsd's bugzilla is now up.  I didn't see an report on bash yesterday, so you maybe you want to file this there (preferable with a patch to fix the port)

**Comment by jrmarino** [comment]
Have you submitted a PR at bugs.freebsd.org on this?

**Comment by sigttou** [comment]
Yes. 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196713

**Comment by jrmarino** [comment]
Thanks.  I added myself to "CC" over there.  I'll close this ticket here to defer to that one.
