### ISSUE TITLE
WITH_NEW_XORG still in x11-servers/xorg-server/Makefile.DragonFly

### ISSUE THREAD

**Issue by davshao** [DragonFlyBSD/DPorts#132]
Building x11-servers/xorg-server seems to fail unless in /etc/make.conf
WITH_NEW_XORG="YES"
or equivalent is defined.

Doing a grep on dports for WITH_NEW_XORG reveals that x11-servers/xorg-server is the one port with a Makefile, here Makefile.DragonFly, that still has a line

if defined(WITH_NEW_XORG)

**Comment by jrmarino** [comment]
Thanks, it's fixed.  ftigeot updated it in Deltaports 3 days ago when he removed the default setting from make.conf, but I didn't know about it so I didn't know to regenerate that port.

**Comment by jrmarino** [comment]
btw, this problem only affected dev branch.  The 3.8 and 4.0 branches still define WITH_NEW_XORG by default.
