### ISSUE TITLE
PostgreSQL 9.4 does not start

### ISSUE THREAD

**Issue by Rolinh** [DragonFlyBSD/DPorts#133]
After a fresh installation of `postgresql94-server-9.4.0` from dports and doing a:
```
# /usr/local/etc/rc.d/postgresql initdb
```
It is still not possible to start the server:
```
Shared object "libpq.so.5" not found, required by "pg_ctl"
```

Version 9.3 works perfectly fine.

**Comment by jrmarino** [comment]
what is output of "ldd /usr/local/bin/pg_ctl"

and what is output of "ls /usr/local/lib/libpq*" ?

**Comment by Rolinh** [comment]
```
/usr/local/bin/pg_ctl:
	libpq.so.5 => not found (0)
	libintl.so.8 => /usr/local/lib/libintl.so.8 (0x800833000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x800a3d000)
	libc.so.8 => /lib/libc.so.8 (0x800c55000)
```
And
```
-rw-r--r--  1 root  wheel  297814 Jan  5 23:16 /usr/local/lib/libpq.a
lrwxr-xr-x  1 root  wheel      12 Jan  5 23:16 /usr/local/lib/libpq.so -> libpq.so.5.7
lrwxr-xr-x  1 root  wheel      12 Jan  5 23:16 /usr/local/lib/libpq.so.5 -> libpq.so.5.7
```
ha, there we go: `libpq.so.5.7` is missing.

**Comment by jrmarino** [comment]
It's probably a dragonfly-specific issue.  libpq.so.5.7 is not supposed to be installed (in other words, ports expects the SHLIB to be one level, "5", not two levels e.g. "5.7").

libpq.so.5.7 was clearly produced but not packaged.  There's no workaround -- so I'd say this is a confirmed bug.  Let me take a look at it.

**Comment by Rolinh** [comment]
Ok thanks @jrmarino. Ping me if you need anything.

**Comment by jrmarino** [comment]
Here's something you can do:
step 1) copy databases/postgresql93-server/Makefile.DragonFly to databases/postgresql94-server
step 2) build postgresql93-client from source
step 3) install it and make the same checks as before.

That might fix it. If it does, I'll add that file to dports

**Comment by jrmarino** [comment]
I'm testing the above in muscles, it looks like it fixes it to me.  I'll push to dports shortly.

**Comment by jrmarino** [comment]
Fix pushed to dports.  Probably tomorrow sometime the dev ports (4.2) will be updated and should have the fixed version of pg94-client and server

**Comment by Rolinh** [comment]
I confirm the fix.
