### ISSUE TITLE
[patch] lang/gcc47 fails to build with lang/gcc5

### ISSUE THREAD

**Issue by zrj-rimwis** [DragonFlyBSD/DPorts#136]
````
In file included from .././../gcc-4.7.4/gcc/cp/except.c:990:0:
cfns.gperf: At top level:
cfns.gperf:101:1: error: 'gnu_inline' attribute present on 'libc_name_p'
cfns.gperf:26:14: error: but not here
````
Missing conditional gnu_inline attribute in prototype, and cast to int suggested by gperf.
Simple workaround:
https://drive.google.com/file/d/0BwWNLQDwiOxtYnJSRm1Dam9XTU0/view?usp=sharing

**Comment by jrmarino** [comment]
patch incorporated, thanks!
a680cc6ef758e2f15be8bf8209da51658e02d710

**Comment by PtOH** [comment]
Thank you so much for the content of the patch, but can I get some hint on how to apply the patch to the problem? I am just starting to learn. Thank you!
