### ISSUE TITLE
Use freebsd upower backend instead of dummy

### ISSUE THREAD

**Issue by jorisgio** [DragonFlyBSD/DPorts#137]
Right now, upower uses the dummy backend and not the freebsd one, which is kind of working, as far as i can tell. One could add --with-backend=freebsd  ton CONFIGURE_ARGS to change this

**Comment by jrmarino** [comment]
Do you recommend that we add that via Makefile.DragonFly?

I don't have an opinion on this, I'll do what you suggest we should.

**Comment by jorisgio** [comment]
I think we should. I've not done extended testing but it works better than the dummy backend, at least.

**Comment by jrmarino** [comment]
ok, done: e8fe21f91c7c6103ebcbcb74c53443b260043a63
