### ISSUE TITLE
net/beanstalkd  fix to compile

### ISSUE THREAD

**Issue by sysadminmike** [DragonFlyBSD/DPorts#138]
Hi,

After 'make extract' copy the freebsd.c to dragonfly.c and it builds fine.

Not fully tested that all is working but it starts up ok

    nobody      3017  0.0  0.0   6492    888 ??  I0Ls    5:54PM   0:00.00 daemon: /usr/local/bin/beanstalkd[3018] (daemon)
    nobody      3018  0.0  0.1   4504   1216 ??  I1L     5:54PM   0:00.01 /usr/local/bin/beanstalkd

/usr/dports/net/beanstalkd # make extract
/!\ WARNING /!\
WITH_NEW_XORG and WITHOUT_NEW_XORG knobs were removed and have no effect
WITH_KMS was removed and has no effect

===>  License MIT accepted by the user
===>  Found saved configuration for beanstalkd-1.9
===>   beanstalkd-1.9 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by beanstalkd-1.9 for building
===>  Extracting for beanstalkd-1.9
=> SHA256 Checksum OK for beanstalkd-1.9.tar.gz.

/usr/dports/net/beanstalkd # cp /usr/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005/freebsd.c /usr
/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005/dragonfly.c

/usr/dports/net/beanstalkd # make
===>  Patching for beanstalkd-1.9
===>   beanstalkd-1.9 depends on executable: gmake - found
===>  Configuring for beanstalkd-1.9
===>  Building for beanstalkd-1.9
gmake[2]: Entering directory '/usr/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005'
cc -pipe -O2 -fno-strict-aliasing   -c -o dragonfly.o dragonfly.c
cc -pipe -O2 -fno-strict-aliasing   -c -o conn.o conn.c
cc -pipe -O2 -fno-strict-aliasing   -c -o file.o file.c
cc -pipe -O2 -fno-strict-aliasing   -c -o heap.o heap.c
cc -pipe -O2 -fno-strict-aliasing   -c -o job.o job.c
cc -pipe -O2 -fno-strict-aliasing   -c -o ms.o ms.c
cc -pipe -O2 -fno-strict-aliasing   -c -o net.o net.c
cc -pipe -O2 -fno-strict-aliasing   -c -o primes.o primes.c
cc -pipe -O2 -fno-strict-aliasing   -c -o prot.o prot.c
cc -pipe -O2 -fno-strict-aliasing   -c -o sd-daemon.o sd-daemon.c
cc -pipe -O2 -fno-strict-aliasing   -c -o serv.o serv.c
cc -pipe -O2 -fno-strict-aliasing   -c -o time.o time.c
cc -pipe -O2 -fno-strict-aliasing   -c -o tube.o tube.c
cc -pipe -O2 -fno-strict-aliasing   -c -o util.o util.c
./verc.sh >vers.c
cc -pipe -O2 -fno-strict-aliasing   -c -o walg.o walg.c
cc -pipe -O2 -fno-strict-aliasing   -c -o main.o main.c
cc -pipe -O2 -fno-strict-aliasing   -c -o vers.o vers.c
cc   -o beanstalkd dragonfly.o conn.o file.o heap.o job.o ms.o net.o primes.o prot.o sd-daemon.o serv.o time.o tube.o util.o vers.o walg.o main.o 
gmake[2]: Leaving directory '/usr/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005'
===>  Staging for beanstalkd-1.9
===>   Generating temporary packing list
install  -s -o root -g wheel -m 555 /usr/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005/beanstalkd /usr/obj/dports/net/beanstalkd/work/stage/usr/local/bin
install  -o root -g wheel -m 444 /usr/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005/doc/beanstalkd.1  /usr/obj/dports/net/beanstalkd/work/stage/usr/local/man/man1
install  -o root -g wheel -m 0644 /usr/obj/dports/net/beanstalkd/work/kr-beanstalkd-f40e005/doc/protocol.txt /usr/obj/dports/net/beanstalkd/work/stage/usr/local/share/doc/beanstalkd
====> Compressing man pages (compress-man)
===> Staging rc.d startup script(s)

Broken log:  http://muscles.dragonflybsd.org/latest-failures/logs/beanstalkd-1.9.log

**Comment by jrmarino** [comment]
done, thanks: e1702e65f84a1ad932855a5f97bcbd883ca56511
