### ISSUE TITLE
net-mgmt/nagios-pf-plugin patch to compile

### ISSUE THREAD

**Issue by sysadminmike** [DragonFlyBSD/DPorts#139]
After running 'make patch' on freebsd port 

/usr/obj/dports/net-mgmt/nagios-pf-plugin/work/kian-nagios-pf-plugin-2aba423/check_pf.c

     --- check_pf.c  2015-02-16 20:42:06.896348000 +0000
    +++ check_pf.c-dragonfly        2015-02-16 20:42:14.602564000 +0000
    @@ -20,7 +20,7 @@
     #include <sys/fcntl.h>
     #include <net/if.h>
     #include <netinet/in.h>
    -#include <net/pfvar.h>
    +#include <net/pf/pfvar.h>
 
     #include <err.h>
     #include <limits.h>

**Comment by Rolinh** [comment]
Something's wrong with your diff.

**Comment by sysadminmike** [comment]
fixed - i think i forgot lt and gt would be seen as html elements

**Comment by jrmarino** [comment]
I'll get to this soon, I've been busy ironing out ports for gcc-5

**Comment by jrmarino** [comment]
Thanks, it's in ports now: 545275b8fe1a84fff8df5d5b46bb57766b41553f
