### ISSUE TITLE
Firefox crash when playing a Youtube video (no Flash)

### ISSUE THREAD

**Issue by olleharstedt** [DragonFlyBSD/DPorts#141]
Release 4.

**Comment by jrmarino** [comment]
This is another example of a run-time issue.  It's not out of scope of a "dports issue" per se, but in practical terms, it is.  There's not enough manpower to chase down run time issue on 22,000 ports, especially a report such as this that provides practically zero information (what video?  is there a trace?   is there a core dump?  etc, etc)

**Comment by olleharstedt** [comment]
Any Youtube video. Easy to reproduce. Firefox is not any port, I'd say.

**Comment by jrmarino** [comment]
I can't chase this down.  If you have a solution or at least identify the problem, feel free to reopen.

Also at least one new version of firefox has been released since.

**Comment by olleharstedt** [comment]
Will upgrade and try again, maybe it's fixed. Thanks for your time.

**Comment by jrmarino** [comment]
If it is still doing it, try to find someone to help you diagnose it.  I simply do not have the time for runtime errors, other people need to contribute to fix port errors like this.
