### ISSUE TITLE
Resizing Xfce4 Terminal window unexpectedly closes on master

### ISSUE THREAD

**Issue by davshao** [DragonFlyBSD/DPorts#143]
Using current master both for world / kernel and for dports and rebuilding everything from scratch, resizing an Xfce4 Terminal window causes an immediate close.  This has been observed on multiple machines running either Intel integrated graphics or Radeon 4xxx.

I don't know whether to report this issue for dports here or at the DragonFly BSD bug tracker since this may be similar to previously observed problems with a libedit update.

**Comment by jrmarino** [comment]
I suggest opening a bug report because run-time issues are basically out of scope of what I'm doing.  I rely on being given patches and fixes for that (in other words, I don't come up with the fixes myself, that's simply too much for one person on volunteer basis)

**Comment by jrmarino** [comment]
moved to https://bugs.dragonflybsd.org/issues/2800
