### ISSUE TITLE
databases/postgis21 does not build

### ISSUE THREAD

**Issue by ejc123** [DragonFlyBSD/DPorts#145]
when option 'RASTER' is selected.  It fails in linking because of a failed reference to strnicmp.  It turns out that raster/rt_core/rt_api.h has an #if defined(__FreeBSD__) that fixes it.  Adding defined(__DragonFly__) fixes the problem.
databases/postgis20 has the same defined() checks so I added them there too.
I'll submit a PR shortly.

**Comment by jrmarino** [comment]
can you try adding "USES+= alias" to the port makefile instead, and tell me if that works?

**Comment by ejc123** [comment]
That seems to work.  I assume that's preferred over a patch?  I'll resubmit my PR.

**Comment by jrmarino** [comment]
I don't need a patch for something that simple.
however, this stupid port doesn't pass testing (pre-existing I think)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/postgresql/extension/postgis--2.1.3--%%PORTVERSION%%.sql
Error: Orphaned: share/postgresql/extension/postgis--2.1.4--%%PORTVERSION%%.sql
Error: Orphaned: share/postgresql/extension/postgis_tiger_geocoder--2.1.3--%%PORTVERSION%%.sql
Error: Orphaned: share/postgresql/extension/postgis_tiger_geocoder--2.1.4--%%PORTVERSION%%.sql
Error: Orphaned: share/postgresql/extension/postgis_topology--2.1.3--%%PORTVERSION%%.sql
Error: Orphaned: share/postgresql/extension/postgis_topology--2.1.4--%%PORTVERSION%%.sql
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.

**Comment by ejc123** [comment]
Those files could be added to pkg-plist.  They exist in the postgis extensions dir and, as I understand it, could be useful if upgrading from 2.1.[3-4] to 2.1.5

**Comment by jrmarino** [comment]
the point is that they must be added to pkg-plist or removed from stage directory, otherwise the port is in error.

It's a maintainer issue but I can fix it without asking.

**Comment by jrmarino** [comment]
Fixed in ports (will take time to trickle down).

I set USES+= alias only if RASTER option is used with "RASTER_USES= alias"

http://www.freshports.org/commit.php?category=databases&port=postgis21&files=yes&message_id=201504011921.t31JL1An050952@svn.freebsd.org
