### ISSUE TITLE
krb5 missing errortable and dports config

### ISSUE THREAD

**Issue by edwberger** [DragonFlyBSD/DPorts#148]
Tried to use the kerberos version of rsh from pkg krb5-appl and got undefined symbol "add_error_table" in krb5.so message

/usr/local/bin/rsh -x filefetch@watchdog.psc.edu cat hosts/hosts.psc
/usr/local/lib/libkrb5.so: Undefined symbol "add_error_table"

building krb5 in /usr/dports/security gives same error.

**Comment by jrmarino** [comment]
link it with libcom_err

**Comment by jrmarino** [comment]
ah, i thought you were trying to use libkrb5.so on a separate project.  I misread.

**Comment by jrmarino** [comment]
This is nasty.
/usr/lib/libcom_error.so.3 exists.
so does /usr/local/lib/libcom_error.so.3

the linker is picking up the base com_err library.  One of these needs a different SO number.

**Comment by edwberger** [comment]
Hi John,
Thanks for looking into it.
linker magic is currently beyond my experience level.
-
Ed Berger
eberger@psc.edu

**Comment by jrmarino** [comment]
This was related to old libcom_err being in base.  It's been removed.
