### ISSUE TITLE
cyrus-sasl2-gssapi has heimdal as default kerberos option

### ISSUE THREAD

**Issue by edwberger** [DragonFlyBSD/DPorts#149]
pkg ins cyrus-sasl-gssapi tries to pull in security/heimdal
even though other packages seem to use MIT as the default 
(I tried adding a couple of cyrus- packages and it wanted to install both MIT and HEIMDAL)

dport has Makefile.DragonFly 
  OPTIONS_DEFAULT= HEIMDAL
It probably should be
 OPTIONS_DEFAULT= MIT
to match other package defaults.

**Comment by jrmarino** [comment]
Did you verify the MIT default actually works?  Many of these packages are limited to 1 or no gssapi options depending on what builds (freebsd has heimdal in base which is the difference).

It's a big mess.  But make sure these actually build when the suggested option.

**Comment by edwberger** [comment]
Hi John,

I built it under dports after changing the option, but haven't tested it 
yet.
My work place has sendmail configured to use it for user authentication 
against kerberos.
I can test that out later this week, using the same sendmail config as I 
put on
the linux mailers.

The CentOS 7.1 rpm of cyrus-gssapi uses MIT kerberos.

-
Ed Berger
eberger@psc.edu

**Comment by jrmarino** [comment]
It's not a per-port issue.  On a system, one can either have Kerberos or heimdal, but not both because they install the same files in the same places.

Basically ports has to "pick one" for the default.  I think actually heimdal "won" although It might be better to switch everything to MIT kerberos due to the issues we have with libcom_err.

**Comment by jrmarino** [comment]
cyrus-sasl-gssapi was intentionally set to HEIMDAL.  What are the other cyrus ports that are set to MIT?  I can switch those too.

**Comment by jrmarino** [comment]
No feedback so assume issue resolved.
