### ISSUE TITLE
Node package suggests installing www/npm, which doens't exist. 

### ISSUE THREAD

**Issue by cgag** [DragonFlyBSD/DPorts#150]
I tried working around this by removing --without-npm, but it seems to install npm to /usr/obj/dports/www/node/work/stage/usr/local/bin/npm instead of /usr/local/bin.

**Comment by jrmarino** [comment]
"suggests".  It's just text somebody wrote.

npm doesn't build in poudriere.  Nobody has been able to fix it.  It's disabled for a reason.

What is it exactly you are reporting?  That npm is not in dports?  what do you want to see happen?

**Comment by cgag** [comment]
I don't know, I just know that I wanted to use node w/ npm and found the results of installing node misleading.  Ideally www/npm would be there, otherwise, maybe just delete the text or change it to note that npm isn't available?

**Comment by jrmarino** [comment]
Somebody (not me) needs to provide the real fix for npm.  It's generally understood that sometimes messages written for FreeBSD don't always apply and also that several hundred ports are not available due to not building.
