### ISSUE TITLE
virtualbox-ose-additions is missing

### ISSUE THREAD

**Issue by GustafHaglund** [DragonFlyBSD/DPorts#152]
Hi,

I testing Dragonfly BSD in a virtual machine and want to set up Xorg to later install Mate, and I think the virtualbox-ose-additions package is needed for the mouse. I have tried to follow a guide for FreeBSD (but customized it after Dragonfly BSD -> dports), but it failed because the package virtualbox-ose-additions is missing.

https://www.freebsd.org/doc/en/books/handbook/virtualization-guest.html

I would be glad if virtualbox-ose-additions would be added into the dports tree (/usr/dports/emulators/virtualbox-ose-additions).

Thank you,
Gustaf Haglund

**Comment by jrmarino** [comment]
It's impossible, it requires freebsd kernel source.  Obviously that's freebsd specific.

**Comment by GustafHaglund** [comment]
Ah, ok, thank you for responding.
