### ISSUE TITLE
finance/frontaccouting: missing dependencies

### ISSUE THREAD

**Issue by ma-su** [DragonFlyBSD/DPorts#153]
Additional PHP module dependencies (hash, ctype and zlib) are needed for frontaccounting to function properly.
The following should be changed in its DPort Makefile:

USE_PHP+=	mysql mysqli openssl session hash ctype zlib

**Comment by jrmarino** [comment]
Wouldn't this be an issue for FreeBSD ports as well?

What indications are given to highlight the missing dependencies?

**Comment by ma-su** [comment]
Yes, I assume that would also affect the FreeBSD port, but I cannot 
definitely tell.

Without these modules, I cannot add a new accounting year which is 
critical and the plugins/languages/COP setup does not work i.e., the 
pages do not contain the lists of what is available.

One can spot calls to missing PHP functions when running frontaccounting 
in "debug" mode.

**Comment by jrmarino** [comment]
I opened problem report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200265

**Comment by jrmarino** [comment]
the new version of frontaccounting is in dports, version 2.3.24

available only by source ATM ofc

**Comment by ma-su** [comment]
Thanks!
