### ISSUE TITLE
pkg package target doesn't work 

### ISSUE THREAD

**Issue by markuspf** [DragonFlyBSD/DPorts#154]
With today's `poudriere-devel` on `master`, I can't even manage to poudriere build pkg. The build fails in the package stage, not being able to find pkg-static. I can only speculate that this is due to staging support (or broken staging support).

**Comment by jrmarino** [comment]
for now, find /usr/local/share/poudriere/include/common.sh.dragonfly

and comment out the PKG_CREATE line

**Comment by jrmarino** [comment]
Okay, I added a patch to poudriere-devel and bumped it so that it at least works out of the box (must build from /usr/dports now, not in binary packages yet)
