### ISSUE TITLE
devel/git fails to build with HTMLDOCS is enabled

### ISSUE THREAD

**Issue by ryuo** [DragonFlyBSD/DPorts#155]
My attempts to build devel/git with HTMLDOCS enabled fails with the following log below:

===>  License GPLv2 accepted by the user
===>  Found saved configuration for git-2.4.0
===>   git-2.4.0 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by git-2.4.0 for building
===>  Extracting for git-2.4.0
===>  License GPLv2 accepted by the user
===>  Found saved configuration for git-2.4.0
===>   git-2.4.0 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by git-2.4.0 for building
=> SHA256 Checksum OK for git-2.4.0.tar.xz.
=> SHA256 Checksum OK for git-manpages-2.4.0.tar.xz.
=> SHA256 Checksum OK for git-htmldocs-2.4.0.tar.xz.
-xf: not found
*** Error code 127

Stop.
make[2]: stopped in /usr/dports/devel/git
*** Error code 1

Stop.
make[1]: stopped in /usr/dports/devel/git
*** Error code 1

Stop.
make: stopped in /usr/dports/devel/git

**Comment by jrmarino** [comment]
untested fix: 8f92711997faed6908d298df1e756a6ba612d956

It should work though.
