### ISSUE TITLE
Netatalk has wrong lockfile location

### ISSUE THREAD

**Issue by cHolzberger** [DragonFlyBSD/DPorts#157]
Netatalk tries to use lock file /var/spool/locks/netatalk while /var/spool/lock/netatalk would be right. 

please add  "--with-lockfile=/var/spool/lock/netatalk“ to CONFIGURE_OPTS.

**Comment by jrmarino** [comment]
CONFIGURE_OPTS?  Do you mean CONFIGURE_ARGS?

There is no mention of CONFIGURE_OPTIONS on net/netatalk3 port

**Comment by cHolzberger** [comment]
yeah, i mean CONFIGURE_ARGS

**Comment by jrmarino** [comment]
okay, done.
