### ISSUE TITLE
Nethack 3.4.3

### ISSUE THREAD

**Issue by shamazmazum** [DragonFlyBSD/DPorts#160]
Can you please add the newest version of nethack into port collection?  You can use a port from FreeBSD, only 2 files need to be patched. Here is the patch (wanted to use Github Gist, but this caused my browser to hang up):

http://pastebin.com/CU69NSvY
http://pastebin.com/0yjyh20z

I have no idea why permissions of perm file need to be changed, otherwise call to link() will fail and the game won't start if run by user. But it works this way.

**Comment by jrmarino** [comment]
okay, thanks!
3e64d5919295d7268fe1bcfc4ce99be085d8643b

**Comment by shamazmazum** [comment]
Thanks for answering so fast. Can you please check pkg-plist.patch? It's rejected for some reason and pkg-plist is not patched.

Can you also add nethack34-nox11 version? No patching is required.

**Comment by jrmarino** [comment]
it's rejecting because the patch has dos (windows) line endings.
The best way to request changes is via github pull request on DragonFlyBSD/Deltaports by the way.  I had to do this manually and I was rushed for another reason
