### ISSUE TITLE
rtorrent broken after upgrade

### ISSUE THREAD

**Issue by tdfbsd** [DragonFlyBSD/DPorts#162]
I was using rtorrent 0.9.4-2 (and associated libtorrent) from dports. Today, I upgraded to DFBSD master (v4.3.1.518.g11356-DEVELOPMENT) and went through the bullet proof upgrade process to replace all my dport packages. After this, rtorrent fails instantly with the following unhelpful error message:

rtorrent: Could not find '='.

**Comment by jrmarino** [comment]
dunno.  that string has some hits on google but always seems to point to a bad configuration.  I think you'll have to dig in a bit.

**Comment by tdfbsd** [comment]
On Sun, Sep 20, 2015 at 1:08 PM, jrmarino <notifications@github.com> wrote:

> dunno. that string has some hits on google but always seems to point to a
> bad configuration. I think you'll have to dig in a bit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonFlyBSD/DPorts/issues/162#issuecomment-141829158>
> .
>
That's what I thought too but I switched to a "default" .rtorrent.rc file
(no luck) and then removed the file and still got the same message.
Besides, the versions of rtorrent and libtorrent didn't change with the
upgrade, so my existing rtorrent.rc file should work.

Tim

**Comment by jrmarino** [comment]
agreed, but I still don't know.  That's why I say you'll probably have to figure out at least what's wrong.  It might be caused by some other port and not any change on dfly.

**Comment by tdfbsd** [comment]
On Sun, Sep 20, 2015 at 1:35 PM, jrmarino <notifications@github.com> wrote:

> agreed, but I still don't know. That's why I say you'll probably have to
> figure out at least what's wrong. It might be caused by some other port and
> not any change on dfly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonFlyBSD/DPorts/issues/162#issuecomment-141831962>
> .
>
​Found it. I had set LANG=en_US.UTF-8 in login.conf and this causes
rtorrent to die with that error on startup. I'm not sure when I added that
but I think it was around end of august after you made all those ​locale
changes.

**Comment by jrmarino** [comment]
okay, well that's the cause but rtorrent really should behave with LANG set to a legal (and most common) named locale.
Just out of curiousity, does putting LOCALE_STRICT=1 in the environment along with LANG=en_US.UTF-8 change anything?

**Comment by jrmarino** [comment]
also, obviously you can leave LANG set and invoke rtorrent with LANG=C (e.g. env LANG=c rtorrent) or a wrapper that does the same.

**Comment by tdfbsd** [comment]
LOCALE_STRICT=1 doesn't help. FYI, the first line in the main() routine in
rtorrent is setlocale(LC_ALL, "");

Thanks for the tip about running it with env.

Tim

**Comment by jrmarino** [comment]
see man page: https://www.dragonflybsd.org/cgi/web-man?command=setlocale&section=3
The setlocale line is just taking the locale from the environment (versus having rtorrent override it).  Maybe it should be "setlocale(LC_ALL, "C") instead.

**Comment by tdfbsd** [comment]
I'll play around with it some more and maybe send it on to the rtorrent
dev. BTW, I really appreciate all your work on the locales.


Tim

**Comment by jrmarino** [comment]
issue seems to have met its end...
