### ISSUE TITLE
Aircrack-ng for DragonFlyBSD

### ISSUE THREAD

**Issue by shamazmazum** [DragonFlyBSD/DPorts#164]
Hello. Can you please apply this patch for DPorts? http://pastebin.com/kuvgCUB3

It allows net-mgmt/aircrack-ng to work under DragonFlyBSD correctly, building OS-specific source files instead of dummy ones.

Aircrack-ng can be used on DragonFlyBSD after commit 95fef94aedadd9a19dd2a3d6276c73605cae886e

**Comment by shamazmazum** [comment]
I've also sent pull request for DeltaPorts. I hope I did it right, no possibility to check it by myself, sorry.

**Comment by jrmarino** [comment]
acknowledged, moving to Dports pull request
