### ISSUE TITLE
x86-video-intel29 and the renaming of i915kms.ko to i915.ko

### ISSUE THREAD

**Issue by davshao** [DragonFlyBSD/DPorts#166]
For lastest master, the kernel module i915kms.ko was renamed to i915.ko

http://lists.dragonflybsd.org/pipermail/commits/2015-November/458660.html

In x11-drivers/xf86-video-intel29, there is the following patch explicitly mentioning i915kms.ko for src/intel_device.c:
if (ret || 1) {
    if (xf86LoadKernelModule("i915kms")) ret = 

I speculate those currently running master will somewhat accidentally have an non-updated i915kms.ko still in /boot/kernel, but what about those who install DragonFly from scratch after the install image gets updated? And will the eventual update of the above patch still also test for i915ims.ko as well as i915.ko?

**Comment by ftigeot** [comment]
Deltaports had been updated at the same time as the DragonFly kernel sources in order to handle the new situation.
That particular change is now in dports fab174a2d3e023fb25ae710337a4a37b819e5166 .
