### ISSUE TITLE
pstree(1) from sysutils/psmisc does not recognize /proc

### ISSUE THREAD

**Issue by ddbilik** [DragonFlyBSD/DPorts#167]
Utility pstree(1) from sysutils/psmisc expects "linux content" in /proc. In FreeBSD ports this is solved by files/patch-src-pstree.c to teach pstree(1) to read also other types of /proc. Unfortunately, ifdefs in that patch cover just FreeBSD. On DragonFly "the linux code" is compiled and pstree then just says "/proc is empty (not mounted ?)".

Solution is to enlarge those ifdefs:

-#ifdef __FreeBSD__
+#if defined(__FreeBSD__) || defined(__DragonFly__)

I've verified this is sufficient to make pstree(1) work also on DragonFly.

Note: it'd be best to change this directly in FreeBSD ports, but it's DragonFly issue, so I'm reporting here.

**Comment by jrmarino** [comment]
okay, I modified the patch upstream and it will be in dports soon, thanks.
