### ISSUE TITLE
Importing audio/wmsmixer

### ISSUE THREAD

**Issue by ddbilik** [DragonFlyBSD/DPorts#168]
Port audio/wmsmixer is currently not in dports. There is exactly same problem with ifdefs covering only FreeBSD as described in issue #167, but in this case it makes wmsmixer to not compile. Solution again is to enlarge ifdefs via files/patch-mixctl.h:

-#ifdef __FreeBSD__
+#if defined(__FreeBSD__) || defined(__DragonFly__)

I've verified that this is sufficient to make audio/wmsmixer compile and work also on DragonFly.

**Comment by jrmarino** [comment]
A cleaner fix is to add "alias" to the USES definition in the makefile.  That defines __ FreeBSD __ (without spaces) and makes it build like FreeBSD.

In general, if you want to contribute patches, it's best to submit pull requests at DragonFlyBSD/Deltaports (not DragonFlyBSD/DPorts).  The latter is just generated, so fixes have to go into the former.

I've already pushed "USES=alias" upstream to freebsd.
