### ISSUE TITLE
/xports/devel/qt5

### ISSUE THREAD

**Issue by seannaswell** [DragonFlyBSD/DPorts#172]
When attempting `#synth install devel/qmake5` it fails with:

=> qtbase-opensource-src-5.5.1.tar.xz is not in /xports/devel/qt5/distinfo.
=> Either /xports/devel/qt5/distinfo is out of date, or
=> qtbase-opensource-src-5.5.1.tar.xz is spelled incorrectly.
*** Error code 1
Stop.
make: stopped in /xports/devel/qmake5

**Comment by jrmarino** [comment]
update your ports tree.
If it doubt, blow the ports tree away and fetch it again.  (be careful if distfiles/ directory is located instead the directory though)

That error implies older qt5 (5.4) is still listed as current somewhere, so my guess is you only did a partial update on tree (via svn) or portsnap failed if you use that.

**Comment by aswellian** [comment]
Blew away and re-synced, built correctly. Many thanks.

**Comment by jrmarino** [comment]
oh, it was dports?  I think it just wasn't up to date then.  It had many updates since qt5 didn't work.
We were pushing fixes as they came because something was better than nothing.

For some reason I thought this was about FreeBSD ports.

**Comment by aswellian** [comment]
Yes, was dports. Based on your answer it seemed you were thinking FreeBSD, understandable as I was not specific, but decided to do anyway. Git said all was in sync, but build still failed, so blowing away was the right answer. Thanks again.
