### ISSUE TITLE
net-im/gajim misses resolver

### ISSUE THREAD

**Issue by kworr** [DragonFlyBSD/DPorts#174]
As we have no `host`/`nslookup` in world it would benice  to link them from dns/bind-tools for example.

**Comment by jrmarino** [comment]
i actually don't really know what you are suggested.  Perhaps you can submit a pull request to DeltaPorts to illustrate (and ideally I can just merge the fix)?

**Comment by jrmarino** [comment]
Any progress needs to happen in DeltaPorts (ideally using a git pullup request), so closing.
