### ISSUE TITLE
Make benchmarks/wrk work

### ISSUE THREAD

**Issue by sepherosa** [DragonFlyBSD/DPorts#175]
The tarball (patches are in files/):
[wrk.tbz](https://leaf.dragonflybsd.org/~sephe/wrk.tbz)

Example run:
xanadu1:wrk# wrk -c 512 -d 30s  -t 8 --latency http://192.168.3.254/1K.bin
Running 30s test @ http://192.168.3.254/1K.bin
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.78ms   10.63ms 272.51ms   93.81%
    Req/Sec    28.91k     8.47k   60.49k    68.25%
  Latency Distribution
     50%    1.75ms
     75%    4.64ms
     90%   10.62ms
     99%   49.27ms
  6900693 requests in 30.05s, 8.21GB read
Requests/sec: 229608.72
Transfer/sec:    279.84MB

Thanks,
sephe

**Comment by jrmarino** [comment]
Thanks!
967c96d
