### ISSUE TITLE
Two wrk patches

### ISSUE THREAD

**Issue by sepherosa** [DragonFlyBSD/DPorts#177]
[wrk.c patch](https://leaf.dragonflybsd.org/~sephe/patch-wrk.c)
[wrk.h patch](https://leaf.dragonflybsd.org/~sephe/patch-wrk.h)

I am trying to push to the upstream along w/ other patches.  But, well, still in progress.

**Comment by jrmarino** [comment]
done: c5d564e65dc93c3ebd149c430e869cfdad9deda6
