### ISSUE TITLE
Add Xwayland port to DPorts

### ISSUE THREAD

**Issue by peeterm007** [DragonFlyBSD/DPorts#178]
Port of Xwayland, the Xorg server that enables running Xorg clients under DragonFly:

- A simple port based on x11-servers/xorg-server 
- Category: x11-servers
- It builds and installs only one binary: /usr/local/bin/Xwayland
- Tested and runs under (current versions) of wayland/weston 1.9.0  

[xwayland.zip](https://github.com/DragonFlyBSD/DPorts/files/304406/xwayland.zip)

**Comment by jrmarino** [comment]
This was discussed on #IRC and two of developments most connected to this area disagree with this proposed approach.  It was also pointed out that xwayland is useless without mesa-wayland-egl.  Support for xwayland is recommended to be an option on existing packages, not new ones.

**Comment by peeterm007** [comment]
I do not understand the point about "uselessness without mesa-wayland-egl". At the moment, Wayland/Weston runs fine on DragonFly only with the pixman rendering backend. The alternative, native and preferred backend, the wayland-egl along the GL renderer for Weston can be built, but is useless since results in corrupt rendering. Imre Vadasz pointed this out and I can confirm this for i915 too. However, in spite of this Xwayland runs fine with the (current) pixman backend and this enables to run Xorg clients already now; Xwayland does not depend on the presence of wayland-egl. Can you explain what is meant by "xwayland is useless without wayland-egl"?

Agreed it's better to add xwayland on existing packages; I suppose the preferred way is to add as an option to the the wayland package when building the xwayland module.

**Comment by jrmarino** [comment]
I cannot explain it as it is out of my expertise.  Ivadasz has to be involved in such a discussion and essentially bless any and all proposals.  I'll point him to this PR.

**Comment by peeterm007** [comment]
Great, thanks!

**Comment by ivadasz** [comment]
@peeterm007 Thx for looking into this stuff! and for providing some motiviation again :)
