### ISSUE TITLE
audio/pulseaudio is broken and should be removed

### ISSUE THREAD

**Issue by ftigeot** [DragonFlyBSD/DPorts#179]
Some package update brought audio/pulse audio with it, causing my firefox instance to spawn a "pulseaudio process" eating 100% of one core and still failing to play sound.

Removing the pulseaudio package allowed firefox to play sound again.
My hardware is a Haswell desktop mainboard with the snd_hda driver.

Pulseaudio is hopelessly broken and should be removed from dports.

**Comment by jrmarino** [comment]
something is unclear.  Are you saying if pulseaudio is simply installed (outside of firefox) then firefox will detect that and try to use it?

**Comment by ftigeot** [comment]
That's right.
Firefox and no pulseaudio on the system => everything is fine. Youtube videos play nicely (with sound).
Run pkg install pulseaudio and suddenly the same firefox instance is no longer able to play sound. Youtube videos stay frozen and a pulseaudio process eats 100% of a cpu core.
The only sound produced is made by the CPU fan spinning at full speed.

**Comment by jrmarino** [comment]
okay, PA has been removed (bringing some ports with it)
