### ISSUE TITLE
www/chromium should not use /usr/local/etc instead of /etc for policies and native messaging

### ISSUE THREAD

**Issue by nE0sIghT** [DragonFlyBSD/DPorts#180]
Hi,

This was originally reported by me [against FreeBSD chromium port](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212017).
I checked DPort of Chromium and found [same problem in DragonFlyBSD](https://github.com/DragonFlyBSD/DPorts/blob/master/www/chromium/files/patch-chrome_common_chrome__paths.cc#L21).

Below is original bug report text:

I'm not FreeBSD user, but developer of [GNOME Shell integration for Chrome](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome) extension.
Recently FreeBSD user reported that extension not works in FreeBSD.

After debugging this issue we discovered that FreeBSD uses patch that changed path to Chromium policies and Native massaging manifests (https://svn0.us-east.freebsd.org/ports/head/www/chromium/files/patch-chrome_common_chrome__paths.cc).

This patch forces Chromium to search Policies in "/usr/local/etc/chrome/policies" instead of "/etc/chromium/policies" and Native messaging manifests in "/usr/local/etc/chrome/native-messaging-hosts" instead of "/etc/chromium/native-messaging-hosts".

In my opinion this is wrong because those locations are not documented by Google [here](https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-location) and [here](https://www.chromium.org/administrators/linux-quick-start).
No one Chrome developer knows about this FreeBSD patch and other configuration files locations.

If in FreeBSD those settings locations should be moved (because of some OS policies) those changes should be sent upstream and/or properly documented. As for now those silent changes lead to confusion.

**Comment by jrmarino** [comment]
If/When FreeBSD addresses the issue, the fix will trickle down to DragonFly.  I don't think we'd "fork" chromium, we have to let them take the lead.

**Comment by jrmarino** [comment]
As mentioned in the original post, it's been properly reported at:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212017

Unfortunately, the chromium team has yet to acknowledge it.
