### ISSUE TITLE
Binary package cad/ngspice_rework does not show X11 signal window

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DPorts#181]
When trying to plot signals with ngspice, a message "Can't open viewport for graphics." is shown, when the binary package (pkg ins ngspice_rework) is used. When compiled from ports, it works.

In the Makefile of the port, there is no "USES=X11", or whatever this option is named. This is very likely the issue, as during configuration the existance of X11 headers is tested.

**Comment by jrmarino** [comment]
i think the proper thing to do is open a PR against it at https://bugs.freebsd.org/bugzilla/.  The port has an active maintainer and this issue should affect freebsd too.

**Comment by mneumann** [comment]
@jrmarino makes sense to report as PR.

**Comment by mneumann** [comment]
@jrmarino https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212357
