### ISSUE TITLE
devel/readline: Disable TERMCAP option

### ISSUE THREAD

**Issue by tgyurci** [DragonFlyBSD/DPorts#183]
DragonFly does not have libtermcap.so, so linking fails when TERMCAP option is set to readline port.
TERMP option should be removed completely:

```diff
diff --git a/devel/readline/Makefile.DragonFly b/devel/readline/Makefile.DragonFly
index 01fc2c4..8a4494a 100644
--- a/devel/readline/Makefile.DragonFly
+++ b/devel/readline/Makefile.DragonFly
@@ -1,5 +1,6 @@
 USES+= ncurses
-OPTIONS_DEFAULT:= ${DEFAULT_OPTIONS:NTERMCAP}
+OPTIONS_DEFINE:= ${OPTIONS_DEFINE:NTERMCAP}
+OPTIONS_DEFAULT:= ${OPTIONS_DEFAULT:NTERMCAP}

 pre-configure-script:
        ${REINPLACE_CMD} "s/SHOBJ_LDFLAGS =/SHOBJ_LDFLAGS = -lncurses/" ${WRKSRC}/shlib/Makefile.in
```

**Comment by jrmarino** [comment]
we don't remove option definitions.  This option breaks the port.
Removing the default setting is enough.  

Only default settings are guaranteed to build.  There are countless examples of non-default options that will not build (also on FreeBSD for that matter)

**Comment by tgyurci** [comment]
Alright. But there is a typo in it:

```
OPTIONS_DEFAULT:= ${DEFAULT_OPTIONS:NTERMCAP}
```
should be:

```
OPTIONS_DEFAULT:= ${OPTIONS_DEFAULT:NTERMCAP}
```

**Comment by jrmarino** [comment]
hmm, you're right.
