### ISSUE TITLE
Should -D_WITH_GETLINE=1 be stricken from DragonFly dports?

### ISSUE THREAD

**Issue by davshao** [DragonFlyBSD/DPorts#184]
Looking at the port x11-drivers/xf86-video-intel29/Makefile, I see a line:

CFLAGS+=	-D_WITH_GETLINE=1

I have the impression, correct me if I am wrong, that this definition _WITH_GETLINE is only applicable to FreeBSD, and not to DragonFly.  A quick grep shows no other major port that has a similar line.  cscope-ing DragonFly's source seems to show no conflicting getline().

So should all lines with -D_WITH_GETLINE=1 be stricken from DragonFly dports?

**Comment by zrj-rimwis** [comment]
For now these are needed for DragonFly 4.6-release branch.
getline() visibility guards were only removed in 4.7-master in
https://github.com/DragonFlyBSD/DragonFlyBSD/commit/dd9d57c0b10a005bc3a554cc33272f600f43f9cb
