### ISSUE TITLE
enable USB capture in net/libpcap on DragonFly

### ISSUE THREAD

**Issue by jfhg** [DragonFlyBSD/DPorts#185]
As DragonFly's USB subsystem is heavily based on FreeBSD's we can simply enable the USB capture code for FreeBSD in net/libpcap as with attached patch.
USB packets can then be captured with e.g. `/usr/local/sbin/tcpdump -i usbus1 -w /tmp/usb.pkts`.
[patch-pcap-bpf.c.txt](https://github.com/DragonFlyBSD/DPorts/files/650403/patch-pcap-bpf.c.txt)

**Comment by jrmarino** [comment]
thanks, committed: 0bcb0be8408a5ff08d7bb60083929226e39ecb92
