### ISSUE TITLE
Please bump vulnerable Expat to 2.2.1

### ISSUE THREAD

**Issue by hartwork** [DragonFlyBSD/DPorts#190]
Please excuse my posting style.

Vulnerable copy found at:
https://github.com/DragonFlyBSD/DPorts/tree/master/textproc/expat2

Expat 2.2.1 change log:
https://github.com/libexpat/libexpat/blob/master/expat/Changes

Commits that you may need on top:
* https://github.com/libexpat/libexpat/commit/602e6c78ca750c082b72f8cdf4a38839b312959f
* https://github.com/libexpat/libexpat/commit/e5e25fac1698d9ea8dbb2e51c18d1072254b5f4b

Best, Sebastian

**Comment by jrmarino** [comment]
fix happens naturally: https://github.com/DragonFlyBSD/DPorts/commit/2f86b10b14c3144ad39953ea3b89ae99818ccb50

**Comment by hartwork** [comment]
So it compiles fine without extra commits? What's the process of getting from `staged` into `master`? Have a link? Thanks!

**Comment by jrmarino** [comment]
There's no process.  Nobody is supposed to use staged branch, ever.
You just wait until staged is promoted.

**Comment by hartwork** [comment]
Have a link on how promotion works?
