### ISSUE TITLE
Speech Dispatcher should have Libao build make config option enabled by default because of bugs in its oss backend

### ISSUE THREAD

**Issue by am-dxer** [DragonFlyBSD/DPorts#192]
I am totally blind and use the Orca screen reader to access my Dragonfly systems. Orca uses speech dispatcher to provide speech output for blind users. Without the Libao build dependency enabled, speech breaks up and does not function properly because of the problems in the oss backend for speech dispatcher. Enabling this build option allows speech dispatcher to use libao's oss support which works much better. The Libao option is more tested as well because Linux users who don't use pulse use it (The Alsa backend has issues as well).

**Comment by jrmarino** [comment]
A quick check on accessibility/orca reveals that the port doesn't know about libao.  We'll have to customize the freebsd port to support it, so stand by ...

**Comment by jrmarino** [comment]
I exploded the distribution file and there's no mention of libao in orca.
However, the ports version is pretty old, version 3.18.
The current version is 3.24, so perhaps upgrading the version will show libao support.

**Comment by am-dxer** [comment]
Orca depends on speech dispatcher which depends on libao. Speech dispatcher already knows about libao, the switch just has to be enabled. Orca uses its python bindings to talk to speech dispatcher and that works fine.

**Comment by jrmarino** [comment]
okay, that port doesn't have options either, but I see a configuration option when I explode the distribution file.

**Comment by jrmarino** [comment]
correction: it does have option "AO".  I'll set it on by default.

**Comment by am-dxer** [comment]
when I type make config, I get an option to enable libao.
The following information is from the freshports page.
===> The following configuration options are available for speech-dispatcher-0.8.6:
     ALSA=off: ALSA audio architecture support
     AO=off: libao audio library support
     DOCS=on: Build and/or install documentation
     ESPEAK=on: eSpeak speech synthesizer support
     FESTIVAL=off: Festival Speech Synthesis System support
     FLITE=off: Flite speech synthesis engine support
     NAS=off: Network Audio System support
     PULSEAUDIO=off: PulseAudio sound server support
===> Use 'make config' to modify these settings

**Comment by am-dxer** [comment]
Sorry, think you were commenting when I was.

**Comment by jrmarino** [comment]
okay, I've made and tested the change.  It won't be available until I promote the "staged" ports to the master branch.  There's another problem with rust port preventing me from doing that right now.  I'll start building packages when the rust issue is finally sorted out.  package building takes almost 3 days though.

**Comment by am-dxer** [comment]
Thanks so much for taking the time to fix this. I know there is probably not many blind people using DragonFly but it makes my life much easier when installing a new system. I will close this one.
