### ISSUE TITLE
Expat 2.2.2 has been released

### ISSUE THREAD

**Issue by hartwork** [DragonFlyBSD/DPorts#194]
Dear Expat maintainers,

Expat 2.2.2 has been released.  It fixes a few rough egdes that you reported with 2.2.1 and should help reduce the number of downstream patches.  The change log is up at https://github.com/libexpat/libexpat/blob/master/expat/Changes.  Please report bugs for anything new that you run into.

Best

&nbsp;
Sebastian

PS: I would love to send this via e-mail. If you have a mail contact to write to for this, please let me know.

**Comment by jrmarino** [comment]
DPorts basically mirrors FreeBSD ports.  When they get updates, we also get them.
What would typically happen in the case of textproc/expat2 is that port is updated to 2.2.2 and a couple of week later we'd import the fix.  Now multiply by 25,000 ports.

if there is something really special about 2.2.2 that requires IMMEDIATE update, freebsd should be informed.   In rare cases, we could update before FreeBSD, but that causes all kinds of additional maintenance burdens so the impact of leaving expat synced with FreeBSD has to be worse than the additional burden.

I don't know if I am explaining this well enough or not ...

**Comment by hartwork** [comment]
Sounds like it makes sense to notify you with security issues where days matter and leave the rest to the  regular updating process. I suppose we can close the ticket then?

**Comment by jrmarino** [comment]
yep.
