### ISSUE TITLE
sysutils/password-store 1.7.1 broken

### ISSUE THREAD

**Issue by gisenmann** [DragonFlyBSD/DPorts#195]
After updating to version 1.7.1 (from 1.6.5?) running the pass command without arguments gives:

Error: q::c:: is not in the password store.

The problem seems to  be, that the bash builtin getopt is used and not /usr/local/bin/getopt.

The 1.7.1 /usr/local/libexec/pass bash script tries to source /usr/local/libexec/platform/dragonfly.sh
but the package contains /usr/local/libexec/platform/freebsd.sh.

I think either renaming platform/freebsd.sh into platform/dragonfly.sh would solve the problem, or
patching the pass script like in 1.6.5 with the post-patch make target:

@${REINPLACE_CMD} -Ee 's|GETOPT="getopt"|GETOPT="${LOCALBASE}/bin/getopt"|' ${WRKSRC}/src/password-store.sh
@${REINPLACE_CMD} -Ee 's|SHRED="shred -f -z"|SHRED="rm -P -f"|' ${WRKSRC}/src/password-store.sh

**Comment by jrmarino** [comment]
I commit your suggestion.  I assume it's correct.  It built.  1de37f5d8b9b5f385563d2d027ce337e5736a9ca
