### ISSUE TITLE
Bringing kodi to Dports ?

### ISSUE THREAD

**Issue by Myu-Unix** [DragonFlyBSD/DPorts#196]
Hello there,

Is there anything we (the community) can do to bring kodi to Dports ? FreeBSD has it and it looks in good shape (https://www.freshports.org/multimedia/kodi/)

If there's any way to collaborate to make this happening, I would be glad to, any pointers welcome !

Have a good day !

**Comment by jrmarino** [comment]
see: http://muscles.dragonflybsd.org/synth/snap-failures/Report/
then multimedia/kodi => "Issue with multimedia/libcec"
then multimedia/libcec => "Failed build phase"
then log => http://muscles.dragonflybsd.org/synth/snap-failures/multimedia___libcec.log
hundreds of error lines starting with
```
In file included from /construction/multimedia/libcec/libcec-libcec-4.0.2/src/libcec/adapter/AdapterFactory.cpp:34:0:
/construction/multimedia/libcec/libcec-libcec-4.0.2/src/libcec/env.h:92:19: warning: missing terminating " character
 #define LIB_INFO ("git revision: 4.0.2, compiled on Thu Aug 24 15:08:12 UTC 2017 by root@hostname: illegal option -- f
                   ^
In file included from /construction/multimedia/libcec/libcec-libcec-4.0.2/src/libcec/adapter/AdapterFactory.cpp:34:0:
/construction/multimedia/libcec/libcec-libcec-4.0.2/src/libcec/env.h:93:139: warning: missing terminating " character
 usage: hostname [-s] [name-of-host | -r ip-address | -i interface [-4 | -6]] on DragonFly 4.9-SYNTH (x86_64), features: P8_USB, DRM, randr")
                                                                                                                                           ^
In file included from /construction/multimedia/libcec/libcec-libcec-4.0.2/src/libcec/adapter/AdapterFactory.cpp:34:0:
/construction/multimedia/libcec/libcec-libcec-4.0.2/src/libcec/env.h:93:1: error: missing terminating " character
 usage: hostname [-s] [name-of-host | -r ip-address | -i interface [-4 | -6]] on DragonFly 4.9-SYNTH (x86_64), features: P8_USB, DRM, randr")
 ^
```

so you need to fix libcec before you even speak about kodi (which may or may not build out of the box after libcec is fixed).

**Comment by jrmarino** [comment]
note there are many other types of errors present, not just this LIB_INFO one.  see the log.

**Comment by Myu-Unix** [comment]
Hello John,

Thank you for you thorough explanation, much appreciated.

Unfortunately, I don't have the skills the dive deep into this C code... so I'll pass on this one and try to find other ways to help DragonFly :)

Thank you for your work on this project !

Cheers.

**Comment by ahtotaat** [comment]
Couldn't you simply build without multimedia/libcec? Better have it without CEC than not at all.

It's not like most folks running HTPC would need it, only those owning CEC adapter do.

In FreeBSD ports it's optional (by default selected) and multimedia/kodi would build fine with CEC unticked in make menuconfig menu.

**Comment by jrmarino** [comment]
It still doesn't build:
checking pkg-config is at least version 0.9.0... yes
configure: error: unsupported host (x86_64-portbld-dragonfly5.1)
===>  Script "configure" failed unexpectedly.

So it needs at least one patch.  I would guess more.

**Comment by ahtotaat** [comment]
More than one.
"Unsupported host" I found to be fixable but afterwhile I ran into this:
[errors.txt](https://github.com/DragonFlyBSD/DPorts/files/1379015/errors.txt)

I assume it would be trivial to fix if you do know your C/C++, but it's out of my skill-set sadly.

**Comment by jrmarino** [comment]
I got an email, but the comment isn't here?  was it deleted?
The answer is the __FILE issues are relatively common.  They are relatively easy to fix in C, but sometimes impossible to fix in C++.  I've even disabled functionality to work around it in c++ before.
Basically the c++ code is doing something it really shouldn't, something obviously not portable.

**Comment by ahtotaat** [comment]
Yeah, sorry I deleted it after thinking it over. I figured you do have already more than plenty else to do and decided I shouldn't bother you with it.

**Comment by tuxillo** [comment]
multimedia/kodi is now in dports
