### ISSUE TITLE
Please update to uriparser 0.8.5

### ISSUE THREAD

**Issue by hartwork** [DragonFlyBSD/DPorts#198]
Hi!

uriparser 0.8.5 has been released:
https://github.com/uriparser/uriparser/releases

Thanks for updating!

**Comment by jrmarino** [comment]
After https://reviews.freebsd.org/D14250 is committed, it will eventually trickle down to dports.  No active work necessary.

**Comment by hartwork** [comment]
I see, good to know. Thanks!
