### ISSUE TITLE
mate desktop does not run

### ISSUE THREAD

**Issue by constantius24** [DragonFlyBSD/DPorts#203]
After upgrading DFBSD to 5.4 and upgrading Mate to 1.20, Mate desktop boots very slowly and not boot properly  There are two panels but without menus and indicator applets. there arent icons on pulpit. System runs very slowly.

**Comment by tuxillo** [comment]
Do you know if this didn't happen in DFBSD 5.2? I'll try to reproduce it.

**Comment by tuxillo** [comment]
I've just tried and it works as expected. I think you need to have DBus installed and running. Can you please try and let us know?

**Comment by constantius24** [comment]
dbus is installed and running ( checked via top, )
dbus_enable in /etc/rc.conf
yes this has happened since version 5.2.2 after upgrade Mate form 1.18 to 1.20.
The same bug exist in HardenedBSD but they dont not provide any DE support

**Comment by constantius24** [comment]
OK works. I had .xinitrc in /home/user directory with root privilage

**Comment by tuxillo** [comment]
Ok, let's consider this closed then.
