### ISSUE TITLE
haproxy is broken due to libressl

### ISSUE THREAD

**Issue by gjs278** [DragonFlyBSD/DPorts#205]
haproxy doesn't currently build due to libressl. there are patches floating around that may address this. if it is built with openssl it will work I think.

**Comment by tuxillo** [comment]
I believe LibreSSL does not support ASync jobs (https://www.openssl.org/docs/man1.1.0/man3/ASYNC_start_job.html). I'll try and see if it can be built without async for libressl.

**Comment by tuxillo** [comment]
Latest on dports is 2.0.2 right now, closing this issue.
https://github.com/DragonFlyBSD/DPorts/commits/master/net/haproxy
