### ISSUE TITLE
rclone: build fails

### ISSUE THREAD

**Issue by tdfbsd** [DragonFlyBSD/DPorts#206]
The issue with the rclone build is actually due to azure-storage-blob-go failing to build. I've submitted a bug report to the Azure team:
https://github.com/Azure/azure-storage-blob-go/issues/112

**Comment by tdfbsd** [comment]
The Azure team has included this fix in azure-storage-blob-go v.0.6.0. The build can be fixed now by including this command prior to "go build ."
go get github.com/Azure/azure-storage-blob-go@v0.6.0
Or you can wait for rclone to update their dependencies to select v0.6.0

**Comment by tdfbsd** [comment]
The rclone team has updated the dependency for azure-storage-blob-go to v0.6.0 in master, but it missed the cut for the 1.47 release. The dports build will work when 1.48 comes out. Or it can be worked around now as I mentioned earlier.

**Comment by tuxillo** [comment]
net/rclone 1.48 is in freebsd-ports as of July, 20th so it missed this sync, but we'll see if it builds in the next one.

**Comment by tdfbsd** [comment]
This is fixed with the current package build
