### ISSUE TITLE
enable ZMQ by default for net-p2p/litecoin ports

### ISSUE THREAD

**Issue by hxw** [DragonFlyBSD/DPorts#209]
Enable ZMQ functionality in net-p2p/litecoin and net-p2p/litecoin-daemon by default (like the corresponding bitcoin ports)
[ltc.diff.txt](https://github.com/DragonFlyBSD/DPorts/files/3425196/ltc.diff.txt)

**Comment by tuxillo** [comment]
What do you mean? We haven't changed the default port options.

**Comment by tuxillo** [comment]
Ah, net-p2p/bitcoin has the ZMQ enabled in freebsd-ports. FWIW we do not change the freebsd-ports default ourselves unless they interfere with the normal build.

**Comment by hxw** [comment]
Litecoin ports now have ZMQ as default in FreeBSD, will dports be updated to match at some point?

**Comment by tuxillo** [comment]
Yes, in the next sync the new defaults will be picked up.
