### ISSUE TITLE
net-im/telegram-desktop Stop at --  Phase: configure

### ISSUE THREAD

**Issue by noob237** [DragonFlyBSD/DPorts#210]
Telegram client stops at:

`--  Phase: configure

===>  Configuring for telegram-desktop-1.6.7_1
gyp: Undefined variable qt_lib_release_postfix in Telegram/gyp/Telegram.gyp
*** Error code 1

Stop.
make[1]: stopped in /xports/net-im/telegram-desktop
*** Error code 1

Stop.
make: stopped in /xports/net-im/telegram-desktop

--  Termination

Finished: Sunday, 21 JUL 2019 at 11:34:49 UTC
Duration: 00:03:05`

[http://muscles.dragonflybsd.org/synth/snap-failures/net-im___telegram-desktop.log](url)

Please let me know how can I be of any help so this doesn't turn into just a reminder.

Best regards

**Comment by kworr** [comment]
I guess can be closed by now.
