### ISSUE TITLE
Zathura and mupdf can't open pdf anymore

### ISSUE THREAD

**Issue by daftaupe** [DragonFlyBSD/DPorts#212]
Hello,

I'm having issues with zathura and zathura-pdf-mupdf.
I get the following error
`Could not load plugin '/usr/local/lib/zathura/libpdf-mupdf.so' (/usr/local/lib/libmupdf.so.1.16.0: Undefined symbol "jbig2_ctx_new").`

It seems this issue might be related : https://bugs.archlinux.org/task/64154

Regards,

**Comment by zrj-rimwis** [comment]
The graphics/jbig2dec changed API without SONAME change. Try to cleanup pkg cache and force reinstall mupdf package or compile and reinstall from graphics/mupdf from DPorts. New package set is going to be uploaded this week should not have this issue.
