### ISSUE TITLE
security/tinc-1.0.36 on dragonfly:5.8:x86:64 does not create tun/tap interface automatically

### ISSUE THREAD

**Issue by Myu-Unix** [DragonFlyBSD/DPorts#213]
Hello,

In DragonFly 5.6.x, the tinc daemon was able to generate a tun interface automatically (tun0 in the most basic setup)

In 5.8.0, I now need to create the interface manually beforehand then tinc can start properly :

`ifconfig tun create`
`tun0`

Maybe the package needs some adjustements ? (suggested on IRC)

Cheers,

Myu

**Comment by liweitianux** [comment]
A better solution is to update tinc to use `/dev/tun` instead of a specific `/dev/tunX`.
