### ISSUE TITLE
Update devel/radare2 to 4.5.1

### ISSUE THREAD

**Issue by XVilka** [DragonFlyBSD/DPorts#215]
There was a tremendous amount of new features and bugfixes since. We also incorporated patches for DragonFly and more corresponding fixes.
See 
- https://repology.org/project/radare2/versions
- https://github.com/radareorg/radare2/releases/tag/4.5.1

The mentioned DragonFly fixes:
- https://github.com/radareorg/radare2/pull/17274
- https://github.com/radareorg/radare2/pull/17470

**Comment by tuxillo** [comment]
DPorts ports are modified on every synchronization with FreeBSD Ports, which happens roughly every month. 
The current sync is from July in which radare2 version is still 3.7.x:

https://github.com/freebsd/freebsd-ports/commit/c6e5f895932dbc943fea07d7820a121d25ea2b5c

In the next sync we will likely get radare2 4.5.0.

**Comment by tuxillo** [comment]
@XVilka It built fine in **staged** branch, when we merge with **master** it will reflect in repology.
https://github.com/DragonFlyBSD/DPorts/commit/bcecebc9d5dcc401afc0ca96ca9429818b568441

Thanks for taking care!

**Comment by XVilka** [comment]
Thank you!
