### ISSUE TITLE
AOM aq-mode 2 has a regression that causes crashes, fix is available upstream. 

### ISSUE THREAD

**Issue by ILOVEPIE** [DragonFlyBSD/DPorts#218]
you can get the fix with:
`git cherry-pick -n 31257f59a1df72cbbd1399efb780d13a0e433b16`
or by applying this patch:
[3.1.2 Patch](https://bugs.archlinux.org/task/71800?getfile=20619)

**Comment by tuxillo** [comment]
Thanks for the report and the patch. Fixed in:

Deltaports: https://github.com/DragonFlyBSD/DeltaPorts/commit/2eb18d60e51f949783407cf5ac107b1d3cec6fd6
DPorts/staged: https://github.com/DragonFlyBSD/DPorts/commit/ec7a8e917c9823f55eab25ed18457e738c737f4a
