### ISSUE TITLE
miredo gets multiple IPv6 addresses when IPv4 address changes

### ISSUE THREAD

**Issue by phma** [DragonFlyBSD/DPorts#219]
I'm not totally sure what's happening, as my Internet connection does some kind of NAT and occasionally (almost certainly during a thunderstorm, but sometimes elsewhen) drops and has to reconnect. I think the dropping and reconnecting is what triggers the Miredo bug. When the bug happens, ifconfig looks like this:

teredo: flags=8043<UP,BROADCAST,RUNNING,MULTICAST> metric 0 mtu 1500
        inet6 fe80::222:4dff:fe84:bb1d%teredo prefixlen 64 scopeid 0x5
        inet6 fe80::ffff:ffff:ffff%teredo prefixlen 64 scopeid 0x5
        inet6 2001:0:c38c:c38c:2002:602f:bcd3:2f25 prefixlen 128
        inet6 2001:0:c38c:c38c:3c32:5e2f:bcd3:2f18 prefixlen 128
        inet6 2001:0:c38c:c38c:20e2:502f:bcd3:2eb7 prefixlen 128
        groups: tun
        Opened by PID 18239

Restarting miredo results in no address:

teredo: flags=8002<BROADCAST,MULTICAST> metric 0 mtu 1500
        groups: tun

To get a single address, I have to do this:

# /usr/local/etc/rc.d/miredo stop
Stopping miredo.
# ifconfig teredo destroy
# /usr/local/etc/rc.d/miredo start
Starting miredo.

I'm running v6.1.0.3.g70c69-DEVELOPMENT and miredo-1.2.6_6.

**Comment by daftaupe** [comment]
@phma closing this one as it's rather old, and can't really reproduce it myself.
