### ISSUE TITLE
golang port is not updated to latest 1.17.3 version.

### ISSUE THREAD

**Issue by UlasSAYGINIM** [DragonFlyBSD/DPorts#220]
Hi, 
there are security pathes with latest version of golang.
but Dports does not have latest version of golang.

can you update that urgently?

thanks in advance.

**Comment by tuxillo** [comment]
We're already preparing a sync with freebsd ports which brings 1.17.1. It should be available around next week.

**Comment by UlasSAYGINIM** [comment]
can i do my dports? is there any easy or good way? without any complications? can you advise any documentation?

thank you @tuxillo for information and reply. have a nice day.

**Comment by tuxillo** [comment]
There's go-1.17.1,1 now in the binary package set. Are there any other security concers between 1.17.1 and 1.17.3 ?

**Comment by UlasSAYGINIM** [comment]
it seems so. i provided links below, about security information.

now there is go1.17.4 (released 2021-12-02). just seems improvement after 1.7.3.

go1.17.3 (released 2021-11-04) includes security fixes to the archive/zip and debug/macho packages, as well as bug fixes to the compiler, linker, runtime, the go command, the misc/wasm directory, and to the net/http and syscall packages. See the Go 1.17.3 milestone on our issue tracker for details. 

https://go.dev/doc/devel/release#go1.17.minor

https://groups.google.com/g/golang-announce/c/0fM21h43arc

**Comment by tuxillo** [comment]
Current version is: `go version go1.18.3 dragonfly/amd64`
