### ISSUE TITLE
Update calculix-ccx to 2.19

### ISSUE THREAD

**Issue by luzpaz** [DragonFlyBSD/DPorts#224]
repo: https://github.com/DragonFlyBSD/DPorts/tree/master/cad/calculix-ccx

FreeBSD dports is at 2.19 (https://www.freshports.org/cad/calculix-ccx)

**Comment by daftaupe** [comment]
Hello @luzpaz.

Thanks for opening this issue but the dports way is to sync regularly with FreeBSD ports. So if FreeBSD ports already have 2.19, this version will land in DPorts at next sync, which should be 2022Q2 if I'm not mistaken.
Maybe you want to read https://www.dragonflybsd.org/docs/howtos/HowToDPorts/#index6h1 to understand better how ports are being created for DragonFlyBSD from FreeBSD ports.

**Comment by luzpaz** [comment]
Thanks for the explanation
