### ISSUE TITLE
print/texlive-base (2021) Removes Xetex, LuaTex and other things that made TeX useful.

### ISSUE THREAD

**Issue by djireland** [DragonFlyBSD/DPorts#228]
It seems with the update to print/texlive-base, XeTex, LuaTex and other packages are removed. Presumable because they were build from Texlive 2015.

**Comment by tuxillo** [comment]
I'll have a look as soon as I can.

**Comment by tuxillo** [comment]
They will be available as binary packages in the upcoming days, sorry!
