### ISSUE TITLE
graphics/evince won't open PDF giving: Failed to load backend for 'application/pdf': /usr/local/lib/libpoppler.so.117: Undefined symbol "_ZNSt10filesystem7__cxx114path14_M_split_cmptsEv"

### ISSUE THREAD

**Issue by djireland** [DragonFlyBSD/DPorts#229]
While trying to open any PDF in evince I get:

Failed to load backend for 'application/pdf': /usr/local/lib/libpoppler.so.117: Undefined symbol "_ZNSt10filesystem7__cxx114path14_M_split_cmptsEv"

I'm using GNOME Document Viewer 41.3 on 6.2-RELEASE

**Comment by tuxillo** [comment]
Hrm, maybe it requires a different version of libpoppler, I'll have a look.

**Comment by tuxillo** [comment]
Hopefully this fix (https://github.com/DragonFlyBSD/DeltaPorts/commit/657fe3544329d3198276da8d6eb5f4a47f6b58cf) should do the trick. Once you see it in DPorts you can build it yourself with:

```
$ cd /usr/dports/graphics/poppler
$ make -DBATCH reinstall clean
```
And then `evince` should work fine.

If you don't want to build it, just wait a few days and a binary package will be generated. You will see an update for it.
