### ISSUE TITLE
Re-Enable TLS for postfix-current now that openssl is default

### ISSUE THREAD

**Issue by autumnjolitz** [DragonFlyBSD/DPorts#232]
At some point, DragonFly switched back to openssl as the default TLS library.

Unfortunately, the `mail/postfix-current` Makefile.DragonFly excludes the TLS option from postfix due to "LibreSSL being used" when it no longer is.

```
diff --git a/mail/postfix-current/Makefile.DragonFly b/mail/postfix-current/Makefile.DragonFly
index 41a858d2764..b0c5a7be6a5 100644
--- a/mail/postfix-current/Makefile.DragonFly
+++ b/mail/postfix-current/Makefile.DragonFly
@@ -3,7 +3,7 @@ USES+= ssl
 OPTIONS_DEFAULT:=      ${OPTIONS_DEFAULT:NBLACKLISTD}

 # incompatible with LibreSSL
-OPTIONS_EXCLUDE+= TLS
+#OPTIONS_EXCLUDE+= TLS

 # suppress redefine warnings
 dfly-patch:
```

**Comment by tuxillo** [comment]
@autumnjolitz thanks for reporting! I've now merged @daftaupe 's PR and it will be included in the last package sync we do for 2022Q3 this week.
