### ISSUE TITLE
news/inn-current fails to build

### ISSUE THREAD

**Issue by tuxillo** [DragonFlyBSD/DPorts#235]
As reported by Julien ÉLIE, news/inn-current is failing because it is trying to pull blacklist as a dependency. We will try to fix it.

**Comment by Julien-Elie** [comment]
Thanks!
I think removing `--with-blacklist` from the configure flags will fix the build, or in case it is not, change it to `--without-blacklist`.

**Comment by daftaupe** [comment]
Hello,

@Julien-Elie it seems that in staged branch, the Makefile.DragonFly takes care of removing the BLACKLISTD option for inn, see : https://github.com/DragonFlyBSD/DPorts/blob/staged/news/inn/Makefile.DragonFly
inn-current is using some files from inn, maybe that dame Makefil.DragonFly is needed.
I'll try to reproduce later today and report back/open a PR if needed.

**Comment by daftaupe** [comment]
Ok, when the PR will be merged, new/inn-current should be brought to 20220812 snapshot, as provided by FreeBSD ports 2022Q3 branch.

**Comment by Julien-Elie** [comment]
The rebuild worked fine yesterday.  Thanks!

**Comment by daftaupe** [comment]
@Julien-Elie are you using inn-current on DragonFlyBSD regularly ? Just so we can add that port on a sort of watch list maybe.

**Comment by Julien-Elie** [comment]
No I'm not running DragonFlyBSD.  I'm an upstream maintainer of INN and I regularly look at build logs on various platforms to make sure there aren't any bugs to fix.
