### ISSUE TITLE
Running 2X "synth upgrade-system" recompiles rust and 17 ports.

### ISSUE THREAD

**Issue by devosalain** [DragonFlyBSD/DPorts#242]
Running 2X "synth upgrade-system" recompiles rust and 17 ports.
[Running 2X "synth upgrade-system" should recompile nothing. ]

**Comment by daftaupe** [comment]
@devosalain you mean it recompiles the whole batch 2 times without you doing anything to the dports directory ?

For the record, dsynth is now the official tool to build dports on DragonFly.
