### ISSUE TITLE
radare2-cutter: outdated and wrong project name 

### ISSUE THREAD

**Issue by XVilka** [DragonFlyBSD/DPorts#251]
Since Cutter 2.x versions it switched from Radare2 to Rizin as a backend (a fork of Radare2). Meanwhile, Radare2 developers renamed their GUI to "Iaito". Thus, there are two options to proceed:
1. "radare2-cutter" should become just "cutter-re", like it's already called in some distributions (Fedora) (and update to the latest 2.2.1 version)
2.  Rename it to "iaito" and update to the latest version (and update to 5.8.4 version)

Some of the packages called "radare2-cutter", right, but with time they will either update to Rizin-based Cutter, or Radare2-based Iaito (https://repology.org/project/iaito/versions), thus the name is misleading from the point of view of both projects.

**Links for the reference**

- https://cutter.re
- https://github.com/rizinorg/cutter
- https://rizin.re/posts/faq/
- https://github.com/radareorg/iaito
- https://repology.org/project/rizin/versions
- https://repology.org/project/cutter-re/versions

**Comment by daftaupe** [comment]
Hello,

thank you for taking the time to inform us however we're just following what FreeBSD is doing (and applying the patches found in the DeltaPort repo on top of it) for most of the ports, so you better warn on their side and we will inherit the proper naming later when we resync with their ports.

I'm closing that issue for that reason.
