### ISSUE TITLE
Caddy is outdated

### ISSUE THREAD

**Issue by Username404-59** [DragonFlyBSD/DPorts#254]
Could the package be updated to 2.7.4? Thanks in advance

**Comment by daftaupe** [comment]
Hello @Username404-59

we're following FreeBSD ports versions, and right now are working on 2023Q3 branch, which should bring Caddy in version 2.6.4.
Version 2.7.4 is in the main branch of the FreeBSD ports and should arrive with 2023Q4 branch.

**Comment by Username404-59** [comment]
Thanks for the explanation
