### ISSUE TITLE
net/megacmd need machine-id

### ISSUE THREAD

**Issue by kikadf** [DragonFlyBSD/DPorts#256]
To the working functions megacmd need machine-id, what is exist on FreeBSD in /etc/machine-id path, but not on DragonFly. Simple fix is run dbus-uuidgen --ensure as root, what is generate the /var/lib/dbus/machine-id, and megacmd works well.

Would be nice to add an install message to megacmd with this notice.

**Comment by daftaupe** [comment]
thanks for reporting @kikadf

do you mean FreeBSD is having an auto-generated machine-id, so this step is not necessary ?

**Comment by kikadf** [comment]
Yes, FreeBSD (and OpenBSD too) has /etc/machine-id after OS install. FreeBSD generates with [hostid_save](https://github.com/freebsd/freebsd-src/blob/main/libexec/rc/rc.d/hostid_save).
