### ISSUE TITLE
Programs using security/cryptopp crash with illegal instructions

### ISSUE THREAD

**Issue by ftigeot** [DragonFlyBSD/DPorts#79]
While investigating net-p2p/amule crashes, I found out the security/cryptopp library tries to use illegal instructions.

This occurs in the CryptoPP::RandomNumberGenerator::GenerateWord32(unsigned int, unsigned int) method.

And is caused by the use of the shrx x86 instruction:

(gdb output)
Program received signal SIGILL, Illegal instruction.
0x0000000000626b88 in CryptoPP::RandomNumberGenerator::GenerateWord32(unsigned int, unsigned int) ()
=> 0x0000000000626b88 <_ZN8CryptoPP21RandomNumberGenerator14GenerateWord32Ejj+40>:      c4 e2 73 f7 c3  shrx   %ecx,%ebx,%eax

If I'm not mistaken, shrx is a new Haswell instruction, which means programs using the cryptopp library will crash on all machines not using this latest Intel processor generation.

This is most likely caused by a configure issue and is 100% reproductible so far. Locally built cryptopp binaries on an Ivy-Bridge CPU fail to run on this same CPU.

**Comment by iprok** [comment]
Here is the version with mtune=generic.
[blhost-mtune-general.gz](https://github.com/DragonFlyBSD/DPorts/files/2141128/blhost-mtune-general.gz)
